[installer]
host = "https://dl.truckers.vn"
version = "latest"
ets2_root = "D:\\Steam\\steamapps\\common\\Euro Truck Simulator 2"
ats_root = ""

[navigation_sound]
;Volume level on a scale from 0 to 100
volume = 75
